### ISSUE TITLE
kube-ps1 messed up my kubectl bash completion

### ISSUE THREAD

**Issue by sirKaskadir** [jonmosco/kube-ps1#43] opened 2018-03-02 16:17 UTC
Hi!

I've installed `kube-ps1` but it messed my bash completion :( 
It completes commands properly but not resources names (for instance pod names).

It still won't work, even after I've uninstalled kube-ps1.

Some help would be really appreciated, thanks!

**Comment by jonmosco** [comment] 2018-03-02 17:14
Can you provide a screenshot of this behavior?  

Also, when running this, can you start your environment with the `--norc` flag to ensure its not  a user setting?   

Which version of bash are you using?

**Comment by jonmosco** [comment] 2018-03-10 15:56
Any updates regarding this issue you reported?

**Comment by sirKaskadir** [comment] 2018-03-10 21:40
Hi! Sorry for my late response. 
Well it’s hard to give screenshot of a completion. I can give an example: 

kubectl g[tab] 
Will give kubectl get outcome and it work for all other commands. But let’s say that I for instance have a pod named mypod.
If I do:
kubectl logs -f my[tab]. 
Than it won’t give me a name of my pod which is quite painful because I need to copy it now :(
It worked just before I’ve installed kube-ps1.

I’ve tried bash 3 and 4 but it didn’t change anything.
Oh, and I use MacOS, this could make a difference.

**Comment by jonmosco** [comment] 2018-03-10 21:57
Can you try it again with bash --norc, load kube_ps1, and source the bash
completion to rule out this is not related to your configuration?  I can
not reproduce this behavior on bash 3 or 4 vanilla installs.

**Comment by sirKaskadir** [comment] 2018-03-11 09:32
Forgot to mension that I even removed kube-ps1 and it didn’t help.. now I only tried to source completion but it’s every time the same. I can install it back but would it help?

**Comment by jonmosco** [comment] 2018-03-11 10:12
Did you try it with --norc and then sourcing each file (kube_ps1 and the
completion scripts) ?

**Comment by jonmosco** [comment] 2018-03-12 00:32
I have tried to reproduce this issue on several installs (docker), and can not reproduce.  The tab completion seems to be working fine with and without kube-ps1.  What does your configuration look like where you are sourcing the prompt?

**Comment by sirKaskadir** [comment] 2018-03-12 08:40
```
source <(kubectl completion bash)

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
```

Thank you for your efforts!
It might be a coincidence, I'm not saying it's not 😢

**Comment by jonmosco** [comment] 2018-03-12 11:55
What about your PS1 ?

**Comment by thomasliddledba** [comment] 2018-03-14 01:26
I tried to reproduce this issue but can't seem to do it.  Would be interested in your PS1.  Could you post that?
$ uname --all 
```
Linux <machinename> 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

~/.bashrc
```
source <(kubectl completion bash)
KUBE_PS1_SYMBOL_COLOR=green
KUBE_PS1_CTX_COLOR=green
KUBE_PS1_NS_COLOR=magenta
KUBE_PS1_BG_COLOR=''
KUBE_PS1_SYMBOL="⎈"
source ~/myworkdir/kube-ps1/kube-ps1.sh
PS1='[\u@\h] [\w] [$(parse_git_branch)] $(kube_ps1)\n'
PS1+='  |--> '
export PS1
```
![screenshot from 2018-03-13 21-16-31](https://user-images.githubusercontent.com/27060631/37378304-10d22528-2705-11e8-9458-9088fadd7eb2.png)

**Comment by jonmosco** [comment] 2018-03-21 14:27
I am going to close this out today unless its reported as still affecting the command line completion.  Please let me know or I will close it out by EOD.

**Comment by jonmosco** [comment] 2018-03-22 14:17
Closing issue.

**Closed by jonmosco** 2018-03-22 14:17 UTC
