### ISSUE TITLE
K8s symbol breaks long lines wrapping

### ISSUE THREAD

**Issue by bruj0** [jonmosco/kube-ps1#60] opened 2018-08-10 08:49 UTC
The K8s symbol makes the wrapping of long lines to fail:

![](https://i.imgur.com/V7hWSdf.png)

And without:
![](https://i.imgur.com/akVvBgd.png)

Without kube-ps1:

![](https://i.imgur.com/8HnEtat.png)

**Comment by zikes** [comment] 2018-08-10 21:35
Possible explanation: https://unix.stackexchange.com/a/105974/6848

**Comment by jonmosco** [comment] 2018-08-16 11:57
Have you tried the prompt with no configuration (--no-rc and the like) ?  This might be related to other prompt configuration and escaping.

**Comment by bruj0** [comment] 2018-08-17 09:10
I did try without the prompt and it only happens with the prompt and symbol.

**Comment by jonmosco** [comment] 2018-08-27 15:00
Any chance you can try this in a different terminal? (xterm, iTerm2, etc).  I can't reproduce this issue.  Also, can you paste your shell config where you are calling kube_ps1 ?

**Comment by jonmosco** [comment] 2018-10-01 12:00
Can you paste your bash configuration ?

**Comment by jonmosco** [comment] 2018-10-03 14:54
Im going to close this issue.  If you experience anything further, please reopen.

**Closed by jonmosco** 2018-10-03 14:54 UTC

**Comment by linwalth** [comment] 2024-08-01 17:23
Hello! I have this issue, too!

**Comment by jonmosco** [comment] 2024-08-01 17:31
Can you paste a screenshot of this happening and your shell config where you are sourcing kube-ps1?

**Comment by linwalth** [comment] 2024-08-01 17:52
I actually fixed it. I am using iTerm and the locale was not set. Now it is set like this:
![image](https://github.com/user-attachments/assets/e0063bb9-a04c-41ef-a2ad-d5bbf8d89a6a)
With the locale set it wraps the lines correctly.
![image](https://github.com/user-attachments/assets/b0115424-75c0-46a7-ad56-21fb23ac8f87)
I suspect that the terminal itself was not able to properly display the bash output without the locale defined.

**Comment by linwalth** [comment] 2024-08-01 17:52
I hope that this might help other people with this problem!

**Comment by jonmosco** [comment] 2024-08-02 14:07
Thank you for providing that information!
